# Generated by Django 4.1.2 on 2023-03-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title2',
            field=models.CharField(default='mm', max_length=200),
        ),
    ]
