# Generated by Django 4.1.2 on 2023-03-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title2',
        ),
        migrations.AlterField(
            model_name='task',
            name='createddate',
            field=models.DateTimeField(),
        ),
    ]
