# Generated by Django 4.1.2 on 2023-03-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_task_title2_alter_task_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
